### ISSUE TITLE
Click the Upload button and upload the .ocmod.zip file.

### ISSUE THREAD

**Issue by IP-CAM** [playfulsparkle/oc4_bank_transfer_fee#1]
There is no OCMOD file in the Pakage

**Comment by zsoltoroszlany82** [comment]
Thank you for your feedback!

oc4_banktransferfee extension includes all the necessary files for it to function properly, including the install.json file. It has been thoroughly tested on OpenCart version 4.0.2.3, both on the admin and frontend sides, and operates as expected.

Regarding the issue you mentioned: the OpenCart 4 installer does require the package filename to have a .ocmod.zip extension, even though our extension is not technically an OCMOD. This is a requirement imposed by the OpenCart 4 installation system. We have followed this convention to ensure compatibility with the installer, which expects the .ocmod.zip format to allow for a successful installation.

**Comment by IP-CAM** [comment]
Then better remove this Line:
Click the Upload button and upload the **.ocmod.zip** file.

**Comment by zsoltoroszlany82** [comment]
> Then better remove this Line: Click the Upload button and upload the **.ocmod.zip** file.

We've updated the README `2. Upload the Extension Files` section 3. point where you can read `Click the Upload button and upload the banktransferfee.ocmod.zip file.` to avoid confustion.
